services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=33
      - PGID=33
      - TZ=${TZ}
    volumes:
      - ${DATA_ROOT}/heimdall/config:/config
     
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`${HOST}`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      # - "traefik.http.routers.heimdall.priority=60"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.routers.heimdall.tls.certresolver=letsencrypt"
      - "traefik.http.routers.heimdall.service=heimdall"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
    networks:
      - proxy
networks:
  proxy:
    external: true