services:
  chadburn:
    container_name: chadburn
    restart: unless-stopped
    image: premoweb/chadburn:latest
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
