services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    #  - "80:80/tcp"
    environment:
      TZ: "Europe/Prague"
      WEBPASSWORD: "${PASSWORD}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_ROOT}/pihole/dnsmasq.d:/etc/dnsmasq.d
      - ${DATA_ROOT}/pihole/etc-pihole:/etc/pihole
    cap_add:
      - NET_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${HOST}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      # - "traefik.http.routers.pihole.priority=60"
      - "traefik.http.routers.pihole.tls=true"
      # - "traefik.http.routers.pihole.tls.certresolver=letsencrypt"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.regex=^https?://(.*)/?$"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.replacement=https://$1/admin/"
    networks:
      - proxy
networks:
  proxy:
    external: true
