services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - nextcloud

  apache:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT}/nextcloud/data:/var/www/html
      - ${DATA_ROOT}/nextcloud/httpd.conf:/usr/local/apache2/conf/httpd.conf
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.nextcloud-www.rule=Host(`${HOST}`)"
      - "traefik.http.routers.nextcloud-www.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-www.tls=true"
      - "traefik.http.routers.nextcloud-www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud-www.service=nextcloud-www"
      - "traefik.http.services.nextcloud-www.loadbalancer.server.port=80"

      - "traefik.http.routers.nextcloud-www.middlewares=nextcloud_redirectregex, nextcloud-www-header"

      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"

      - "traefik.http.middlewares.nextcloud-www-header.headers.accesscontrolalloworiginlist=https://${HOST}"
      - "traefik.http.middlewares.nextcloud-www-header.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.nextcloud-www-header.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.nextcloud-www-header.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nextcloud-www-header.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud-www-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-www-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nextcloud-www-header.headers.customRequestHeaders.X-Forwarded-Proto=https"

    networks:
      - proxy
      - nextcloud
  nextcloud:
    image: nextcloud:fpm
    container_name: nextcloud
    restart: unless-stopped
    networks:
      proxy:
      database:
      nextcloud:
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      MYSQL_DATABASE: ${MYSQL_NEXTCLOUD_DB}
      MYSQL_USER: ${MYSQL_NEXTCLOUD_USER}
      MYSQL_PASSWORD: ${MYSQL_NEXTCLOUD_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: mariadb
      REDIS_HOST: redis
      APC_SHM_SIZE: 128M
      OPCACHE_MEM_SIZE: 128
      TZ: ${TZ}
      PHP_MEMORY_LIMIT: 1024M
      PHP_UPLOAD_LIMIT: 100G
      OVERWRITEPROTOCOL: https
      # SMTP_HOST: ${SMTP_HOST}
      # SMTP_SECURE: ssl
      # SMTP_PORT: ${SMTP_PORT}
      # SMTP_NAME: ${SMTP_NAME}
      # SMTP_PASSWORD: ${SMTP_PASSWORD}
      # MAIL_FROM_ADDRESS: ${NEXTCLOUD_MAIL}
      NC_DEFAULT_PHONE_REGION: CZ
    links:
      - redis
    depends_on:
      - redis
    devices:
      - /dev/dri
    volumes:
      - ${DATA_ROOT}/nextcloud/data:/var/www/html
      - ${DATA_ROOT}/nextcloud/ffmpeg:/usr/bin/ffmpeg
      - ${MEDIA}:/media
    labels:
      - "chadburn.enabled=true"

      - "chadburn.job-exec.nextcloud-cron.schedule=@every 5m"
      - "chadburn.job-exec.nextcloud-cron.command=php -f cron.php"
      - "chadburn.job-exec.nextcloud-corn.user=www-data"

      - "chadburn.job-exec.nextcloud-preview-pre-generate.schedule=@every 10m"
      - "chadburn.job-exec.nextcloud-preview-pre-generate.command=php occ preview:pre-generate"
      - "chadburn.job-exec.nextcloud-preview-pre-generate.user=www-data"

  collabora:
    image: collabora/code
    restart: unless-stopped
    hostname: collabora
    container_name: nextcloud-collabora
    ports:
      - 9980:9980
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=${TZ}
      - domain=${COLLABORA_DOMAIN}
      - aliasgroup1=https://${HOST}
      - dictionaries=en_US,cz_CZ
      - username=${COLLABORA_USER}
      - password=${COLLABORA_PASSWORD}
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.tls=true"
      - "traefik.http.routers.collabora.tls.certresolver=letsencrypt"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      - "traefik.http.routers.collabora.rule=Host(`${COLLABORA_HOST}`)"
      - "traefik.http.routers.collabora.middlewares=collabora-header"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
      - "traefik.http.middlewares.collabora-header.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.collabora-header.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.collabora-header.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.collabora-header.headers.stsPreload=true"
      - "traefik.http.middlewares.collabora-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.collabora-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.collabora-header.headers.customRequestHeaders.X-Forwarded-Proto=https"
    networks:
      proxy:
      nextcloud:

networks:
  proxy:
    external: true
  database:
    external: true
  nextcloud:
    driver: bridge
