services:
  phpmyadmin:
    hostname: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 9082:80
    environment:
      - PMA_HOST=mariadb # same as service name of db instance
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      # - proxy
      - database
    # you can enable access from the internet if you want
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.nextcloud-pma.rule=Host(`${PHPMYADMIN_HOST}`)"
    #   - "traefik.http.routers.nextcloud-pma.entrypoints=websecure"
    #   - "traefik.http.services.nextcloud-pma.loadbalancer.server.port=80"
    #   - "traefik.http.routers.nextcloud-pma.service=nextcloud-pma"
    #   - "traefik.http.routers.nextcloud-pma.tls.certresolver=letsencrypt"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      # config is misleading, because it contains also the db data
      - ${DATA_ROOT}/mariadb:/config
    networks:
      - database # add service requiring db access to this network
      - nextcloud # or you can add networks for each service

networks:
  # proxy: # traefik network
  #   external: true
  nextcloud:
    external: true
  database:
    name: database
    driver: bridge
