services:
  phpmyadmin:
    hostname: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 9082:80
    links:
      - mariadb:db
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - proxy
      - database
      - nextcloud
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.nextcloud-pma.rule=Host(`${PMA_HOST}`)"
    #   - "traefik.http.routers.nextcloud-pma.entrypoints=websecure"
    #   - "traefik.http.services.nextcloud-pma.loadbalancer.server.port=80"
    #   - "traefik.http.routers.nextcloud-pma.service=nextcloud-pma"
    #   - "traefik.http.routers.nextcloud-pma.tls.certresolver=letsencrypt"

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    hostname: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_ROOT}/mariadb:/config
    networks:
      - database
      - nextcloud

networks:
  proxy:
    external: true
  nextcloud:
    external: true
  database:
    name: database
    driver: bridge
  
